[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

 [[redirects]]
   from = "/api"
   to = "http://159.89.188.76:3000"
   status = 200
   force = true
   headers = {X-From = "Netlify"}
   signed = "API_SIGNATURE_TOKEN"